stages:
  - build
  - docs

build-debug:
  stage: build
  tags:
  - windows
  - msbuild
  script:
  - cd build
  - .\\build-debug.ps1
  artifacts:
    paths:
    - auto/bin/
    expire_in: 1h

build-api-docs:
  stage: docs
  tags:
  - windows
  - msbuild
  script:
  - cd build
  - .\\build-clr-docs.ps1
  artifacts:
    paths:
    - docs/clr-api/
    expire_in: 1h
