name = "Blackburn"
license = "MIT"
licenselink = "https://github.com/yoshiharuyamashita/blackburn/blob/master/LICENSE.md"
description = "A clear, responsive theme constructed using Pure CSS from Yahoo"
homepage = "https://github.com/yoshiharuyamashita/blackburn"
tags = ["blog", "personal", "purecss", "responsive"]
features = ["blog", "personal", "purecss", "responsive"]
min_version = 0.15

[author]
  name = "Yoshiharu Yamashita"
  homepage = "http://yoshiharuyamashita.com"

# If porting an existing theme
[original]
  name = "Responsive side menu"
  homepage = "http://purecss.io/layouts/"
  repo = "https://github.com/yahoo/pure"
